services:
  drupal:
    image: drupal:10-apache
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    restart: always
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=admin

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
