services:
  proxy:
    image: nginx:1.23
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf/:ro
    platform: linux/amd64
  web:
    image: httpd:2
    platform: linux/amd64